{"uuid": "2cb6ab4a-b2e7-4781-b5d4-d447acfab69e", "children": ["08b4c715-aa46-4320-93e1-8439341c8fb0"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom chrome not reachable\n  (Session info: chrome=75.0.3770.142)\n\n", "trace": "  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\python\\pageAutoTest\\Testcase\\conftest.py\", line 23, in login\n    driver = webdriver.Chrome(executable_path=driver_path)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1596608798080, "stop": 1596608810118}], "start": 1596608798080, "stop": 1596608810209}